### ISSUE TITLE
IOS Remote build excludes all folders with the word 'plugins' 

### ISSUE THREAD

**Issue by adamiprinciples** [MicrosoftDocs/cordova-docs#25]
This is a bit of a pain as I'm using durandal for my app structure, which relies on a folder inside (in my case) www > scripts > libs > durandal > plugins

That plugins folder and everything in it fail to get copied so obviously things aren't working so well once deployed.

**Comment by BrianGeppert** [comment]
Thanks for figuring this out.  I was using 'gulp-load-plugins' and it never got installed on my Mac, so it looks like the exclusion is even more indiscriminate than ignoring folders.

**Comment by sdhintGIT** [comment]
None of my plugins that iIve added through the visual studio 2015 designer are copied to the mac for remotebuild. is there a work around for this? It's flat out not using plugins for any vs2015 using the cordova project type. 
is there any other way to push the files over to remote build to generate a working IPA?
