### ISSUE TITLE
keystore absolute paths are not supported

### ISSUE THREAD

**Issue by LordJZ** [MicrosoftDocs/cordova-docs#69]
I was following the guidelines here:
https://github.com/Microsoft/cordova-docs/tree/master/tutorial-package-publish

build.json setup mentions absolute path: `"keystore":"c:\\my-release-key.keystore",`

But copying that brings a build error which makes it clear that absolute paths are not supported in `keystore` item.

**Comment by GabrielGil** [comment]
For Android I am not able to sign release builds with the Json file. I have to override the keystore property from the Json file on the command line.

This command with the json file as described in the [Apache Docs](https://cordova.apache.org/docs/en/edge/guide_platforms_android_tools.md.html#signing-the-app) works fine:
`cordova build android --release -- --keystore android.keystore`

I am using OSX El Capitan and the error I get when I just run `cordova build android --release` is:
```
Reading build config file: /Users/gabriel/Desktop/App-Windows/build.json

/Users/gabriel/Desktop/App-Windows/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
TypeError: Object #<Object> has no method 'isAbsolute'
```

**Comment by jdschuitemaker** [comment]
I got it to work by putting the keystore file in the same folder as the project. Then in your build.json don't use any reference to folders, just your keystore file name.

**Comment by GabrielGil** [comment]
For whoever still being affected by this issue, I'd like to point out that, at least in my case, the problem was the Node version. Works fine for me after upgrading to Node v4.
